var lang = {
    choose_value: 'Search Options',
    search_value: 'Select',
    select_all: 'Select All',
    unselect_all: 'Unselect All',
    selected_option: ' selected',
    dt_search: 'البحث...',
    dt_datatable_pagination_info: 'عرض _START_ ل _END_ ل _TOTAL_ المدخلات',
    dt_next: 'التالية <i class="ph ph-caret-right"></i>',
    dt_previous: '<i class="ph ph-caret-left"></i> السابقة',
    dt_first: '<i class="ph ph-caret-double-left"></i> الأولى',
    dt_last: 'الأخيرة <i class="ph ph-caret-double-right"></i>',
    dt_datatable_pagination_show_menu: 'إظهار _MENU_ المدخلات',
    dt_view_all: 'View All',
    dt_view_less: 'View Less',
    dt_datatable_empty_table: 'No matching records found',
    dt_datatable_info_filtered: '(filtered from _MAX_ total المدخلات)',
    collapse_all: 'إخفاء الكل',
    expand_all: 'إظهار الكل',
    govbh_show: 'إظهار',
    govbh_hide: 'إخفاء',
    swal_ok: 'Ok',
    swal_confirm: 'Confirm',
    swal_cancel: 'Cancel',
    swal_close: 'Close',    
    swal_days: 'Days',
    swal_hours: 'Hours',
    swal_minutes: 'Minutes',
    swal_seconds: 'Seconds',
    govbh_pause_video: 'Click here to pause video.',
    govbh_play_video: 'Click here to play video.',
    govbh_slider_slide_aria_label: 'Slide {0} of {1}',
    govbh_slider_button_aria_label: 'Show slide {0}',
    slide_text: 'شريحة',
    of_text: 'من',
    show_image: 'Show image',
    govbh_yes: 'نعم',
    govbh_no: 'لا',
}